<?php
/**
 * @file
 * Stanford Jumpstart Homepage for Department Sites
 *
 * @author  Caryl Westerberg <cjwest@stanford.edu>
 * Supports homepage functionality for departments sites.
 *
 */

/**
 *  Implements hook_form_FORM_ID_alter()
 *
 * @param $form
 * @param $form_state
 */
function stanford_jumpstart_home_dept_form_stanford_jumpstart_homepage_dashboard_form_alter(&$form, &$form_state) {

  drupal_add_css(drupal_get_path('module', 'stanford_jumpstart_home_dept')
    . '/css/stanford_jumpstart_home_dept.css');

  // Add the stanford_jumpstart_home_dept layouts to the customize design page
  stanford_jumpstart_home_dashboard_add_layouts($form, $form_state, 'stanford_jumpstart_home_dept');

}

/**
 * Implements hook_form_alter().
 */
function stanford_jumpstart_home_dept_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == "system_theme_settings" || $form_id == "stanford_jumpstart_homepage_dashboard_form") {

    $theme = variable_get("theme_default", "stanford_framework");
    $style = theme_get_setting('styles', $theme);

    //Add background screenshot image.
    $bg_img = '/' . drupal_get_path('module', 'stanford_jumpstart_home_dept')
      . '/img/design-styles-soe.png';
    dpm($bg_img);

    $form['design_container']['styles']['#options']['styles-soe'] =
      '<span class="design-style ds-soe" style="background-image: url(' . $bg_img . ')>'
        . t('SoE') . '</span>';
/*
    style="
    background-image: url(/sites/all/modules/stanford/stanford_jumpstart_home/modules/stanford_jumpstart_home_dept/img/design-styles-soe.png);
"
*/

  }
}

/**
 * @param $css
 * Set the SoE styles.
 * See stanford_framework_css_alter()
 */
function stanford_jumpstart_home_dept_css_alter(&$css) {

  $styles = theme_get_setting('styles');

  // Styles variables.
  switch ($styles) {
    case "styles-soe":
      drupal_add_css(drupal_get_path('module', 'stanford_soe_helper') . '/css/soe_helper.css', array(
        'group' => CSS_THEME,
        'media' => 'all',
        'weight' => 100,
        'preprocess' => TRUE
      ));
      break;
    default:
  }
}
